### ISSUE TITLE
Return boolean indicating success

### ISSUE THREAD

**Issue by mandrade2** [oblador/react-native-store-review#88]
Hey there! Thanks for publishing this package. 

Would it be possible to add a boolean indicating whether the user rated the app or not? If so, how can it be done

I'm down to contributing it, just need some hints as I haven't done native development

Thanks in advance!

**Comment by oblador** [comment]
No it's not supported by the underlying APIs because the platform vendors don't want you to use it that way. There's a hacky way to infer this, but I'm a bit cautious to include it as it's indirect and not sure to work across OS versions, but you can try it if you want: https://github.com/oblador/react-native-store-review/pull/37
